service: nextjs
app: demo
tenant: gtwright
plugins:
  - serverless-offline
  - serverless-apigw-binary
frameworkVersion: 1.34.1
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'dev'}
  environment:
    NODE_ENV: prod
    LAMBDA: true
custom: 
  apigwBinary:
    types:
      - '*/*'
functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}