service: nextjs
app: ${self:provider.environment.APP}
tenant: ${self:provider.environment.TENANT}
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'dev'}
  environment:
    NODE_ENV: prod
    LAMBDA: true
    CERTIFICATE_NAME: "*.commoncalendar.org"
    TENANT: gtwright
    APP: demo
    DOMAIN_NAME: "dev.commoncalendar.org"
custom:
  # environment: ${file(env.yml):${self:provider.stage}}
  customDomain:
    domainName: ${self:provider.environment.DOMAIN_NAME}
    stage: ${self:provider.stage}
    certificateName: ${self:provider.environment.CERTIFICATE_NAME}
    createRoute53Record: true
    endpointType: 'edge'
  apigwBinary:
    types:           #list of mime-types 
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}