service: nextjs
app: ${env:APP}
tenant: ${env:TENANT}
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'dev'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
custom:
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    stage: ${self:provider.stage}
    certificateName: ${env:CERTIFICATE_NAME}
    createRoute53Record: true
    endpointType: 'edge'
  apigwBinary:
    types:           #list of mime-types 
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}