service: nextjs
app: demo
tenant: gtwright
plugins:
  - serverless-offline
  # - serverless-domain-manager
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'dev'}
  environment:
    NODE_ENV: prod
    LAMBDA: true
custom: 
  # customDomain:
  #   domainName: ${ssm:/nextjs-starter/domainName-${self:provider.stage}}
  #   stage: ${self:provider.stage}
  #   certificateName: ${ssm:/nextjs-starter/certificateName}
  #   createRoute53Record: true
  #   endpointType: 'edge'
  apigwBinary:
    types:           #list of mime-types 
      - '*/*'
functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}