service: nextjs
app: ${env:APP}
tenant: ${env:TENANT}
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-apigw-binary
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'dev'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    LAMBDA: true
custom:
  environment: ${file(env.yml):${self:provider.stage}}
  # customDomain:
  #   domainName: ${self:custom.environment.DOMAIN_NAME}
  #   stage: ${self:provider.stage}
  #   certificateName: ${self:custom.environment.CERTIFICATE_NAME}
  #   createRoute53Record: true
  #   endpointType: 'edge'
  apigwBinary:
    types:
      - '*/*'

functions:
  next:
    handler: lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{any+}